# -*- coding: utf-8 -*-
"""230906morning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jNYat44wB6jt1WgycnrLuRR22uMjKMT
"""



import tkinter as tk

def increment_count(count_var):
    current_count = int(count_var.get())
    new_count = current_count -1
    count_var.set(new_count)

def decrement_count(count_var):
    current_count = int(count_var.get())
    new_count = current_count + 1
    count_var.set(new_count)

# GUI 창 생성
root = tk.Tk()
root.title("카운터 프로그램")

# 초기 카운트 값 설정
count1 = tk.StringVar(value="0")
count2 = tk.StringVar(value="0")
count3 = tk.StringVar(value="0")

# 프레임 생성
frame1 = tk.Frame(root)
frame1.pack(padx=20, pady=20)
frame2 = tk.Frame(root)
frame2.pack(padx=20, pady=20)
frame3 = tk.Frame(root)
frame3.pack(padx=20, pady=20)

# 라벨 생성
label1 = tk.Label(frame1, textvariable=count1)
label1.pack(side=tk.LEFT)
label2 = tk.Label(frame2, textvariable=count2)
label2.pack(side=tk.LEFT)
label3 = tk.Label(frame3, textvariable=count3)
label3.pack(side=tk.LEFT)

# "감소" 버튼 생성 및 연결
button1_dec = tk.Button(frame1, text="되돌리기", command=lambda: decrement_count(count1))
button1_dec.pack(side=tk.RIGHT)

button2_dec = tk.Button(frame2, text="되돌리기", command=lambda: decrement_count(count2))
button2_dec.pack(side=tk.RIGHT)

button3_dec = tk.Button(frame3, text="되돌리기", command=lambda: decrement_count(count3))
button3_dec.pack(side=tk.RIGHT)

button1 = tk.Button(frame1, text="전대석", command=lambda: increment_count(count1))
button1.pack(side=tk.RIGHT)
button2 = tk.Button(frame2, text="김광호", command=lambda: increment_count(count2))
button2.pack(side=tk.RIGHT)
button3 = tk.Button(frame3, text="양승민", command=lambda: increment_count(count3))
button3.pack(side=tk.RIGHT)

# GUI 루프 시작
root.mainloop()